name: CI Workflow

on:
  push:
    branches:
      - '*' # Runs on all branches
  pull_request:
    branches:
      - '*' # Runs on pull requests to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Yarn Berry
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier Check
        run: yarn run prettier:check

      - name: Build the project
        run: yarn run build

      - name: Run tests
        run: yarn run test
